chore: remove homebrew_core release workflow
It's no longer needed. The last attempt failed with this message:

Error: Whoops, the gibo formula has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that is excluded from autobump list (i.e. it has 'no_autobump!'
method or 'livecheck' block with 'skip'.)